### ISSUE TITLE
Networking tracking

### ISSUE THREAD

**Issue by juaxix** [davidwed/tracy#1]
Hello, I wonder if there is a way to track the network ,similarly to what Unreal Engine do with their [networking insights](https://docs.unrealengine.com/4.27/en-US/TestingAndOptimization/PerformanceAndProfiling/UnrealInsights/NetworkingInsights/). 
Also , how easy could be to inject the general STAT info from Unreal to tracy?
Thanks!

**Comment by davidwed** [comment]
Hello,

initially the repo is a fork of [bitbucket.org/wolfpld/tracy](bitbucket.org/wolfpld/tracy) Now the creator has migrated the repository to Github [https://github.com/wolfpld/tracy](https://github.com/wolfpld/tracy)

I think your issue is better off in the original repo.

Good luck !
