### ISSUE TITLE
No up-to-date build instructions for unix

### ISSUE THREAD

**Issue by aaron-michaux** [davidwed/tracy#2]
Hi, without instructions, it's ambiguous if I'm supposed to use cmake, or meson, and indeed, which projects I can or should build. The pdf manual does list some dependencies, but when it gets to building the server, merely says "good luck"... something like:

```
# Tested on TheDevsDistro X.Y.Z
> mkdir build
> cd build
> cmake -DCMAKE_INSTALL_PREFIX=/path/to/install <OPTIONS> ..
> make -j
> sudo make install
```

**Comment by davidwed** [comment]
https://github.com/davidwed/tracy/issues/1#issuecomment-1123447358
